export const announcements: string[] = [
  "We are delighted to welcome Dr. Aisha Kapoor as our new VP of Engineering. Aisha brings 15 years of experience in scaling engineering teams and previously served as Engineering Director at CloudTech. Please join us in welcoming her aboard!",
  "Promotion Announcement\n\nPlease join me in congratulating Marcus Lee, who has been promoted to Senior Product Manager. Marcus has consistently delivered outstanding results, most notably leading the successful launch of our mobile payment feature.",
  "Office Move Update\n\nWe are relocating to our new headquarters at 200 Innovation Drive, effective August 1. The new space features a state-of-the-art auditorium, collaborative zones, and a rooftop terrace. Packing instructions will be shared next week.",
  "Product Launch — TaskFlow 2.0\n\nWe are excited to announce the release of TaskFlow 2.0, featuring real-time collaboration, AI-powered task prioritization, and seamless Slack integration. Upgrade instructions are available on the internal portal.",
  "Policy Change — Flexible Fridays\n\nStarting next month, we are introducing Flexible Fridays. Employees may adjust their Friday schedule to start between 6 AM and 10 AM, with no core hours. This is part of our commitment to work-life flexibility.",
  "Company Milestone\n\nWe have reached 10,000 active users worldwide. This is a testament to the hard work of every team member. Thank you for making this possible!",
  "Team Expansion\n\nPlease welcome our new cohort of 12 interns joining from top universities across the country. They will be rotating through Engineering, Marketing, and Sales over the next 8 weeks.",
  "Holiday Schedule\n\nThe office will be closed from December 24 through January 2 for the winter break. Please plan your projects accordingly and submit any urgent requests by December 20.",
  "Award Announcement\n\nWe are proud to announce that we have won the 2025 Industry Excellence Award for Best Workplace Culture. This honor reflects your collective dedication and values.",
  "Office Relocation Update\n\nOur London branch is moving to a larger space at 55 King William Street to accommodate our growing team. The move is scheduled for the first weekend of March.",
  "Promotion Announcement\n\nCongratulations to Sarah Mitchell on her promotion to Director of Product Design! Sarah has been instrumental in shaping our design system and elevating our user experience.",
  "Retirement\n\nAfter 28 years of dedicated service, Dr. Robert Chen will be retiring at the end of this month. We will host a farewell gathering on June 28 at 3 PM in the cafeteria.",
  "Partnership Announcement\n\nWe are thrilled to announce a strategic partnership with DataSphere Inc. This collaboration will integrate our platforms and unlock new market opportunities for both companies.",
  "Acquisition News\n\nWe have acquired CloudSync Technologies, a leader in hybrid cloud orchestration. The acquisition will accelerate our roadmap and expand our engineering talent pool.",
  "Product Launch — SyncBoard\n\nWe are launching SyncBoard, our new collaborative whiteboarding tool. It supports real-time drawing, sticky notes, and integration with TaskFlow. Try it today!",
];
