export const api: string[] = [
  "GET /api/v2/users?page=1&limit=50 HTTP/1.1\nAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
  "{\n  \"error\": {\n    \"code\": \"RATE_LIMITED\",\n    \"message\": \"Too many requests. Retry after 30 seconds.\",\n    \"retryAfter\": 30\n  }\n}",
  "POST /api/graphql HTTP/1.1\nContent-Type: application/json\n\n{\"query\":\"mutation { createUser(input: {name: \\\"John\\\", email: \\\"john@example.com\\\"}) { id name }}\"}",
  "WebSocket connection established to wss://api.example.com/events\n{\"type\":\"subscribe\",\"channel\":\"order_updates\",\"token\":\"auth_token_here\"}",
  "HTTP/1.1 201 Created\nLocation: /api/v2/orders/ord_8f7a3b2c\nContent-Type: application/json\nX-Request-Id: req_abc123",
  "DELETE /api/v2/products/prod_9x4y2z HTTP/1.1\nIf-Match: \"etag-abc123\"\nAuthorization: Bearer token_here",
  "{\n  \"id\": \"evt_3kQ8uR5n\",\n  \"type\": \"payment_intent.succeeded\",\n  \"data\": {\n    \"object\": {\n      \"amount\": 2999,\n      \"currency\": \"usd\"\n    }\n  }\n}",
  "PUT /api/v2/profiles/user_42 HTTP/1.1\nContent-Type: application/json\nIdempotency-Key: 7a3f9c2e-b814-4a1d\n\n{\"name\":\"Jane\",\"email\":\"jane@example.com\"}",
  "PATCH /api/v2/articles/art_5f8a HTTP/1.1\nContent-Type: application/json-patch+json\n\n[{\"op\":\"replace\",\"path\":\"/status\",\"value\":\"published\"}]",
  "OPTIONS /api/v2/resource HTTP/1.1\nOrigin: https://app.example.com\nAccess-Control-Request-Method: POST",
  "HTTP/1.1 429 Too Many Requests\nRetry-After: 120\nX-RateLimit-Limit: 100\nX-RateLimit-Remaining: 0",
  "POST /api/v2/webhooks HTTP/1.1\nContent-Type: application/json\n\n{\"url\":\"https://myapp.com/webhook\",\"events\":[\"order.created\",\"payment.completed\"]}",
  "GET /api/v2/search?q=programming+typescript&filters[language]=en&sort=relevance HTTP/1.1",
  "HEAD /api/v2/health HTTP/1.1\nX-API-Version: 2024-01\nAccept: application/json",
  "{\n  \"@context\": \"https://www.w3.org/ns/hydra/core\",\n  \"@id\": \"/api/users\",\n  \"member\": [\n    {\"@id\": \"/api/users/1\", \"name\": \"Alice\"}\n  ]\n}",
];
