export const comments: string[] = [
  "// TODO: Implement caching layer for frequently accessed user data\n// This will reduce database load by approximately 60%",
  "/**\n * Calculates the shipping cost based on weight and destination.\n * @param weight - Package weight in kilograms\n * @param destination - ISO country code\n * @returns Shipping cost in USD\n */",
  "// FIXME: Race condition occurs when two users update the same record\n// Need to implement optimistic locking with version numbers",
  "# This is a temporary workaround for the API rate limiting issue\n# TODO: Replace with proper retry logic using exponential backoff",
  "<!-- TODO: Add alt text to all images for accessibility compliance -->\n<!-- WCAG 2.1 AA compliance required by Q3 -->",
  "/**\n * @deprecated Use processOrderV2 instead which supports split payments.\n * This method will be removed in version 3.0.\n */",
  "// HACK: Using setTimeout to wait for DOM to render\n// This is not ideal but the MutationObserver approach was causing memory leaks",
  "/* Performance note: This query runs on every page load.\n * Consider adding pagination or caching if it becomes slow.\n * Currently averages 45ms on production data */",
  "// Security: Validate and sanitize all user input before passing to SQL\n// Use parameterized queries to prevent SQL injection attacks",
  "# Configuration for development environment\n# Override these values in production via environment variables",
  "/**\n * @template T\n * @param {T} input - The input value\n * @param {(value: T) => boolean} predicate - Test function\n * @returns {T | undefined} The first matching element or undefined\n */",
  "// REVIEW: This algorithm has O(n^2) complexity. Consider using a hash map\n// for better performance when handling large datasets.",
  "/*\n * Architecture Decision: Using event sourcing for order processing\n * Context: Need complete audit trail for all order state changes\n * Status: Accepted\n */",
  "# pylint: disable=too-many-arguments\n# This function needs all parameters for proper error reporting",
  "// NOTE: The following regex validates RFC 5322 email addresses\n// It covers 99.97% of all valid email formats in use",
];
