export const config: string[] = [
  "{\n  \"compilerOptions\": {\n    \"target\": \"ES2022\",\n    \"module\": \"ESNext\",\n    \"moduleResolution\": \"bundler\",\n    \"strict\": true,\n    \"jsx\": \"react-jsx\"\n  }\n}",
  "module.exports = {\n  test: /\\.[jt]sx?$/,\n  exclude: /node_modules/,\n  use: {\n    loader: 'babel-loader',\n    options: { presets: ['@babel/preset-env', '@babel/preset-react'] }\n  }\n};",
  "{\n  \"semi\": true,\n  \"trailingComma\": \"all\",\n  \"singleQuote\": false,\n  \"printWidth\": 100,\n  \"tabWidth\": 2,\n  \"arrowParens\": \"always\"\n}",
  "import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({\n  plugins: [react()],\n  build: { outDir: 'dist', sourcemap: true }\n});",
  "{\n  \"extends\": [\"next/core-web-vitals\", \"prettier\"],\n  \"rules\": {\n    \"@typescript-eslint/no-unused-vars\": \"error\",\n    \"react/no-unescaped-entities\": \"off\"\n  }\n}",
  "/** @type {import('tailwindcss').Config} */\nmodule.exports = {\n  content: ['./src/**/*.{ts,tsx}'],\n  theme: { extend: { colors: { primary: '#6366f1' } } }\n};",
  "{\n  \"name\": \"my-app\",\n  \"version\": \"1.0.0\",\n  \"scripts\": {\n    \"dev\": \"next dev\",\n    \"build\": \"next build\",\n    \"start\": \"next start\",\n    \"lint\": \"eslint . --ext .ts,.tsx\"\n  },\n  \"dependencies\": {\n    \"next\": \"15.0.0\",\n    \"react\": \"19.0.0\"\n  }\n}",
  "module.exports = {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {},\n  },\n};",
  "{\n  \"compilerOptions\": {\n    \"types\": [\"node\", \"jest\", \"@testing-library/jest-dom\"],\n    \"baseUrl\": \".\",\n    \"paths\": {\n      \"@/*\": [\"./src/*\"]\n    }\n  },\n  \"include\": [\"src\", \"tests\"]\n}",
  "import { defineConfig } from 'tsup';\nexport default defineConfig({\n  entry: ['src/index.ts'],\n  format: ['cjs', 'esm'],\n  dts: true,\n  splitting: false,\n  sourcemap: true,\n  clean: true,\n});",
  "{\n  \"version\": \"1.0\",\n  \"formatters\": [\"typescript\", \"css\", \"html\", \"json\"],\n  \"linters\": [\"eslint\", \"stylelint\"],\n  \"plugins\": [\"@biomejs/biome\"]\n}",
  "import type { PlaywrightTestConfig } from '@playwright/test';\nconst config: PlaywrightTestConfig = {\n  testDir: './e2e',\n  retries: 2,\n  use: {\n    baseURL: 'http://localhost:3000',\n    screenshot: 'only-on-failure',\n  },\n};",
  "{\n  \"name\": \"my-service\",\n  \"version\": \"0.1.0\",\n  \"main\": \"dist/index.js\",\n  \"scripts\": {\n    \"build\": \"tsup\",\n    \"test\": \"vitest run\",\n    \"release\": \"semantic-release\"\n  }\n}",
  "// tsconfig paths\n\"paths\": {\n  \"@components/*\": [\"./src/components/*\"],\n  \"@lib/*\": [\"./src/lib/*\"],\n  \"@hooks/*\": [\"./src/hooks/*\"]\n}",
  "export default {\n  experimental: {\n    turbo: {\n      rules: {\n        '*.svg': ['@svgr/webpack'],\n      },\n    },\n  },\n};",
];
