export const cpp: string[] = [
  "template<typename T>\nT max(T a, T b) {\n    return (a > b) ? a : b;\n}",
  "std::vector<int> nums = {1, 2, 3, 4, 5};\nauto it = std::find_if(nums.begin(), nums.end(), [](int n) { return n % 2 == 0; });",
  "class Singleton {\nprivate:\n    static Singleton* instance;\n    Singleton() {}\npublic:\n    static Singleton* getInstance() {\n        if (!instance) instance = new Singleton();\n        return instance;\n    }\n};",
  "int* ptr = new int(42);\nstd::unique_ptr<int> uptr = std::make_unique<int>(42);\nstd::shared_ptr<int> sptr = std::make_shared<int>(42);",
  "std::map<std::string, int> scores;\nscores[\"alice\"] = 95;\nscores[\"bob\"] = 87;\nfor (const auto& [name, score] : scores) {\n    std::cout << name << \": \" << score << '\\n';\n}",
  "auto lambda = [](int x, int y) -> int { return x + y; };\nstd::cout << lambda(3, 4) << std::endl;",
  "template<typename T>\nconcept Numeric = std::is_arithmetic_v<T>;\n\ntemplate<Numeric T>\nT square(T x) { return x * x; }",
  "std::vector<int> v = {1, 2, 3, 4, 5};\nstd::transform(v.begin(), v.end(), v.begin(), [](int n) { return n * 2; });",
  "auto ptr = std::make_shared<int>(42);\nauto weak = std::weak_ptr<int>(ptr);",
  "constexpr int factorial(int n) {\n    return n <= 1 ? 1 : n * factorial(n - 1);\n}\nstatic_assert(factorial(5) == 120);",
  "struct Point { int x; int y; };\nauto [x, y] = Point{10, 20};",
  "std::string s = \"hello \";\ns += \"world\";\nauto sub = s.substr(0, 5);",
  "template<typename... Args>\nauto sum(Args... args) {\n    return (args + ...);\n}\nint total = sum(1, 2, 3, 4);",
  "auto print = [](const auto& val) { std::cout << val << '\\n'; };\nprint(42); print(3.14); print(\"hello\");",
  "class Resource {\npublic:\n    Resource() { acquire(); }\n    ~Resource() { release(); }\n    Resource(const Resource&) = delete;\n    Resource& operator=(const Resource&) = delete;\n};",
];
