export const css: string[] = [
  ".container {\n    display: flex;\n    justify-content: center;\n    align-items: center;\n    gap: 1rem;\n    flex-wrap: wrap;\n}",
  ".grid {\n    display: grid;\n    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\n    gap: 1.5rem;\n    padding: 2rem;\n}",
  "@keyframes fadeIn {\n    from { opacity: 0; transform: translateY(10px); }\n    to { opacity: 1; transform: translateY(0); }\n}\n\n.animate {\n    animation: fadeIn 0.3s ease-out;\n}",
  "@media (max-width: 768px) {\n    .sidebar {\n        display: none;\n    }\n    .main-content {\n        grid-template-columns: 1fr;\n    }\n}",
  ":root {\n    --primary: #0070f3;\n    --secondary: #6b7280;\n    --radius: 8px;\n    --shadow: 0 2px 8px rgba(0,0,0,0.1);\n}\n\n.card {\n    border-radius: var(--radius);\n    box-shadow: var(--shadow);\n    background: var(--primary);\n}",
  "@container (min-width: 400px) {\n    .card { font-size: 1.2rem; }\n}",
  "@layer base, components, utilities;\n@layer base {\n    h1 { font-size: 2rem; }\n}",
  ".card:has(img) { border: 2px solid gold; }\n.form:has(:invalid) { border-color: red; }",
  ".parent {\n    & .child { color: blue; }\n    & > .direct { font-weight: bold; }\n}",
  "@media (prefers-reduced-motion: no-preference) {\n    @keyframes slide { from { translate: 0; } to { translate: 100%; } }\n}",
  ".container {\n    container-type: inline-size;\n    container-name: sidebar;\n}",
  "@supports (selector(:has(*))) {\n    .modern { display: block; }\n}",
  ".scroll-timeline {\n    animation: fadeIn linear;\n    animation-timeline: scroll();\n}",
  ".custom-scrollbar::-webkit-scrollbar { width: 8px; }\n.custom-scrollbar::-webkit-scrollbar-thumb { background: #888; }",
  ".clamp-text {\n    display: -webkit-box;\n    -webkit-line-clamp: 3;\n    -webkit-box-orient: vertical;\n    overflow: hidden;\n}",
];
