export const docker: string[] = [
  "FROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build",
  "FROM python:3.12-slim AS base\nRUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates\nCOPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv",
  "services:\n  app:\n    build: .\n    ports:\n      - \"3000:3000\"\n    environment:\n      NODE_ENV: production\n      DATABASE_URL: postgres://user:pass@db:5432/app",
  "docker build -t myapp:latest --build-arg NODE_ENV=production --platform linux/amd64 .\ndocker push registry.example.com/myapp:latest",
  "docker run -d --name myapp -p 8080:80 --restart unless-stopped --memory 512m --cpus 0.5 myapp:latest",
  "services:\n  db:\n    image: postgres:16-alpine\n    volumes:\n      - postgres_data:/var/lib/postgresql/data\n    environment:\n      POSTGRES_DB: myapp\n      POSTGRES_PASSWORD: ${DB_PASSWORD}",
  "FROM nginx:alpine AS production\nCOPY --from=builder /app/dist /usr/share/nginx/html\nCOPY nginx.conf /etc/nginx/conf.d/default.conf\nEXPOSE 80\nHEALTHCHECK CMD wget -qO- http://localhost/ || exit 1",
  "docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --scale app=3\ndocker compose logs -f --tail=100 app",
  "FROM golang:1.22 AS builder\nWORKDIR /app\nCOPY go.mod go.sum ./\nRUN go mod download\nCOPY . .\nRUN CGO_ENABLED=0 go build -o /app/server ./cmd/server",
  "services:\n  redis:\n    image: redis:7-alpine\n    ports:\n      - \"6379:6379\"\n    volumes:\n      - redis_data:/data\n    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}",
  "docker network create --driver overlay --attachable myapp_network\ndocker service create --name web --replicas 3 --network myapp_network --publish 80:80 nginx:alpine",
  "FROM rust:1.78 AS builder\nRUN cargo build --release --target x86_64-unknown-linux-musl\nFROM alpine:3.20\nCOPY --from=builder /app/target/release/myapp /usr/local/bin/myapp",
  "docker system df\ndocker system prune -af --volumes\ndocker builder prune -af --filter until=24h",
  "services:\n  app:\n    build:\n      context: .\n      args:\n        - NODE_ENV=development\n    volumes:\n      - .:/app\n      - /app/node_modules\n    command: npm run dev",
  "docker secret create db_password secrets/db_password.txt\ndocker service create --secret db_password --name app -e DB_PASSWORD_FILE=/run/secrets/db_password myapp:latest",
];
