export const errors: string[] = [
  "TypeError: Cannot read properties of undefined (reading 'map')\n    at renderUserList (components/UserList.tsx:45:12)\n    at processChild (react-dom.development.js:1234:18)",
  "Error: ENOENT: no such file or directory, open '/app/config/production.json'\n    at Object.openSync (fs.js:462:3)\n    at Object.readFileSync (fs.js:364:35)",
  "Unhandled Promise Rejection: Error: Connection timeout after 30000ms\n    at Timeout._onTimeout (/app/node_modules/pg-pool/index.js:98:15)\n    at listOnTimeout (internal/timers.js:549:17)",
  "RangeError: Maximum call stack size exceeded\n    at Object.stringify (<anonymous>)\n    at Object.stringify (<anonymous>)\n    at JSON.parse (native)\n    at circularReference",
  "Error: listen EADDRINUSE: address already in use :::3000\n    at Server.setupListenHandle [as _listen2] (net.js:1318:16)\n    at listenInCluster (net.js:1367:12)",
  "SequelizeConnectionError: could not connect to PostgreSQL: Connection refused\n    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:182:24)",
  "Error: getaddrinfo ENOTFOUND api.example.com\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)\n    Cause: DNS resolution failed for 'api.example.com'",
  "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory\n 1: 0x1008ff1e node::Abort() [/usr/local/bin/node]",
  "Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (_http_outgoing.js:526:11)\n    at ServerResponse.json (response.js:82:20)",
  "MongoServerError: E11000 duplicate key error collection: app.users index: email_1 dup key: { email: \"test@example.com\" }",
  "Error: Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.other.com/data.",
  "SyntaxError: Unexpected token '}', \"{\"status\":\"error\",\"message\":\"Invalid input\"}\" is not valid JSON\n    at JSON.parse (<anonymous>)\n    at parseResponse (api.ts:34:16)",
  "Error: Request failed with status code 503 Service Unavailable\n    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)",
  "ValidationError: \"email\" must be a valid email. \"age\" must be greater than or equal to 18.\n    at module.exports (/app/node_modules/joi/lib/types/object.js:478:24)",
  "Error: self-signed certificate in certificate chain\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)\n    at TLSSocket.emit (events.js:315:20)\n    Cause: Certificate issuer not trusted",
];
