export const git: string[] = [
  "git checkout -b feature/login-page && git commit -m \"Add login page component\" && git push -u origin feature/login-page",
  "git rebase -i HEAD~5 && git log --oneline --graph --all --decorate",
  "git cherry-pick a1b2c3d && git diff --cached --stat",
  "git stash push -m \"WIP: auth refactor\" && git stash list && git stash pop stash@{0}",
  "git log --since=\"2024-01-01\" --author=\"alice\" --format=\"%h %s\" --no-merges",
  "git bisect start HEAD v1.0 && git bisect run npm test",
  "git worktree add -b feature/payment ../payment-feature main",
  "git submodule add https://github.com/example/lib.git libs/mylib && git submodule update --init --recursive",
  "git filter-branch --env-filter 'export GIT_AUTHOR_NAME=\"New Name\"' -- --all",
  "git reflog expire --expire=now --all && git gc --aggressive --prune=now",
  "git sparse-checkout set src/ docs/ tests/ && git sparse-checkout init --cone",
  "git merge-base --is-ancestor feature/main main && echo 'Fast-forward possible'",
  "git diff --name-status HEAD~3 HEAD -- '*.ts' '!*.test.ts'",
  "git tag -a v2.0.0 -m \"Release version 2.0.0\" && git push origin v2.0.0",
  "git log --all --graph --pretty=format:'%Cred%h%Creset %Cgreen(%cr)%Creset %s'",
];
