export const html: string[] = [
  "<form action=\"/submit\" method=\"POST\">\n    <label for=\"email\">Email:</label>\n    <input type=\"email\" id=\"email\" name=\"email\" required aria-describedby=\"email-help\">\n    <span id=\"email-help\">We\\'ll never share your email.</span>\n    <button type=\"submit\">Submit</button>\n</form>",
  "<table>\n    <thead><tr><th>Name</th><th>Role</th><th>Status</th></tr></thead>\n    <tbody>\n        <tr><td>Alice</td><td>Admin</td><td>Active</td></tr>\n        <tr><td>Bob</td><td>User</td><td>Inactive</td></tr>\n    </tbody>\n</table>",
  "<header role=\"banner\">\n    <nav aria-label=\"Main navigation\">\n        <ul>\n            <li><a href=\"/\" aria-current=\"page\">Home</a></li>\n            <li><a href=\"/about\">About</a></li>\n            <li><a href=\"/contact\">Contact</a></li>\n        </ul>\n    </nav>\n</header>",
  "<article>\n    <h1>Understanding Semantic HTML</h1>\n    <p>Semantic elements like <code>&lt;main&gt;</code>, <code>&lt;section&gt;</code>, and <code>&lt;aside&gt;</code> improve accessibility.</p>\n    <time datetime=\"2024-03-15\">March 15, 2024</time>\n</article>",
  "<div class=\"card\" role=\"region\" aria-labelledby=\"card-title\">\n    <h2 id=\"card-title\">Product Name</h2>\n    <p>Description of the product goes here.</p>\n    <button aria-label=\"Add to cart\">Buy Now</button>\n</div>",
  "<dialog id=\"myDialog\">\n  <p>Content inside dialog</p>\n  <button onclick=\"document.getElementById('myDialog').close()\">Close</button>\n</dialog>",
  "<details>\n  <summary>Click to expand</summary>\n  <p>Hidden content revealed here with smooth animation.</p>\n</details>",
  "<input list=\"browsers\" name=\"browser\" />\n<datalist id=\"browsers\">\n  <option value=\"Chrome\">\n  <option value=\"Firefox\">\n  <option value=\"Safari\">\n</datalist>",
  "<form onsubmit=\"event.preventDefault()\">\n  <input type=\"search\" name=\"q\" placeholder=\"Search...\" />\n  <button type=\"submit\">Go</button>\n</form>",
  "<div inert>\n  <p>This content is not interactive or focusable.</p>\n  <a href=\"#\">This link cannot be clicked</a>\n</div>",
  "<picture>\n  <source srcset=\"image.webp\" type=\"image/webp\">\n  <source srcset=\"image.jpg\" type=\"image/jpeg\">\n  <img src=\"image.jpg\" alt=\"Fallback image\">\n</picture>",
  "<output name=\"result\" for=\"a b\"></output>\n<script>\n  const a = 5, b = 10;\n  document.querySelector('output').value = a + b;\n</script>",
  "<div popover id=\"popover1\">Popover content here</div>\n<button popovertarget=\"popover1\">Toggle Popover</button>",
  "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n<link rel=\"stylesheet\" href=\"styles.css\">",
  "<progress value=\"70\" max=\"100\">70%</progress>\n<meter value=\"0.7\" min=\"0\" max=\"1\" low=\"0.3\" high=\"0.8\">70%</meter>",
];
