export const javascript: string[] = [
  "async function fetchData(url) {\n    try {\n        const response = await fetch(url);\n        if (!response.ok) throw new Error(`HTTP ${response.status}`);\n        return await response.json();\n    } catch (err) {\n        console.error('Fetch failed:', err);\n    }\n}",
  "const numbers = [1, 2, 3, 4, 5];\nconst doubled = numbers.map(n => n * 2);\nconst evens = numbers.filter(n => n % 2 === 0);\nconst sum = numbers.reduce((acc, n) => acc + n, 0);",
  "function createCounter() {\n    let count = 0;\n    return function() {\n        count++;\n        return count;\n    };\n}",
  "document.querySelectorAll('.accordion-item').forEach(item => {\n    item.addEventListener('click', () => {\n        item.classList.toggle('active');\n        const panel = item.querySelector('.panel');\n        panel.style.display = panel.style.display === 'block' ? 'none' : 'block';\n    });\n});",
  "new Promise((resolve, reject) => {\n    setTimeout(() => resolve('Done'), 1000);\n}).then(result => console.log(result)).catch(err => console.error(err));",
  "const obj = { a: 1, b: 2 };\nconst proxy = new Proxy(obj, {\n    get(target, prop) { return prop in target ? target[prop] : 42; }\n});",
  "function* idGenerator() {\n    let id = 0;\n    while (true) yield id++;\n}\nconst gen = idGenerator();",
  "const wm = new WeakRef({ data: 'cache me' });\nsetTimeout(() => console.log(wm.deref()?.data), 1000);",
  "const now = Temporal.Now.plainDateTimeISO();\nconst due = now.add({ days: 7 });\nconsole.log(due.toString());",
  "const arr = [1, [2, [3]]];\nconsole.log(arr.flat(2));\nconsole.log(arr.flatMap(x => [x, x * 2]));",
  "class MyClass {\n    accessor #privateField = 42;\n    getValue() { return this.#privateField; }\n}",
  "const grouped = Object.groupBy([\n    { name: 'Alice', role: 'admin' },\n    { name: 'Bob', role: 'user' }\n], ({ role }) => role);",
  "const a = [1, 2, 3, 4];\nconst b = [5, 6, 7, 8];\nconst merged = [...a, ...b];\nconst [first, ...rest] = merged;",
  "const handler = {\n    apply(target, thisArg, args) {\n        return target(...args).toUpperCase();\n    }\n};",
  "const cache = new Map();\nconst key = { id: 1 };\ncache.set(key, 'value');\nconsole.log(cache.get(key));",
];
