export const java: string[] = [
  "public class Main {\n    public static void main(String[] args) {\n        System.out.println(\"Hello, World!\");\n    }\n}",
  "List<String> items = new ArrayList<>();\nitems.stream()\n    .filter(s -> s.startsWith(\"A\"))\n    .map(String::toUpperCase)\n    .collect(Collectors.toList());",
  "public interface Repository<T, ID> {\n    Optional<T> findById(ID id);\n    List<T> findAll();\n    T save(T entity);\n    void deleteById(ID id);\n}",
  "try (Connection conn = dataSource.getConnection()) {\n    PreparedStatement stmt = conn.prepareStatement(\"SELECT * FROM users WHERE id = ?\");\n    stmt.setInt(1, userId);\n    ResultSet rs = stmt.executeQuery();\n} catch (SQLException e) {\n    logger.error(\"Database error\", e);\n}",
  "@Entity\n@Table(name = \"users\")\npublic class User {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n    @Column(nullable = false)\n    private String name;\n    @Column(unique = true)\n    private String email;\n}",
  "public record Person(String name, int age) {}\nvar p = new Person(\"Alice\", 30);\nSystem.out.println(p.name());",
  "CompletableFuture.supplyAsync(() -> fetchData())\n    .thenApply(String::toUpperCase)\n    .exceptionally(e -> \"fallback\");",
  "List<Integer> nums = List.of(1, 2, 3, 4, 5);\nvar sum = nums.stream().reduce(0, Integer::sum);",
  "Optional<String> name = Optional.ofNullable(getName());\nvar display = name.orElse(\"Unknown\");",
  "var list = new ArrayList<>(List.of(\"a\", \"b\", \"c\"));\nlist.removeIf(s -> s.equals(\"b\"));",
  "module com.example.app {\n    exports com.example.api;\n    requires com.example.utils;\n}",
  "try (var stream = Files.lines(Path.of(\"data.txt\"))) {\n    stream.forEach(System.out::println);\n}",
  "var numbers = List.of(1, 2, 3, 4, 5, 6);\nvar evenSquares = numbers.stream()\n    .filter(n -> n % 2 == 0)\n    .map(n -> n * n)\n    .toList();",
  "Predicate<String> nonEmpty = s -> !s.isEmpty();\nvar result = Stream.of(\"a\", \"\", \"b\").filter(nonEmpty).count();",
  "sealed interface Shape permits Circle, Rectangle {}\nrecord Circle(double radius) implements Shape {}\nrecord Rectangle(double w, double h) implements Shape {}",
];
