export const json: string[] = [
  '{\n  "user": {\n    "id": 42,\n    "name": "Alice Smith",\n    "email": "alice@example.com",\n    "roles": ["admin", "editor"]\n  }\n}',
  '{\n  "status": "ok",\n  "data": {\n    "items": [\n      {"id": 1, "title": "First Item"},\n      {"id": 2, "title": "Second Item"}\n    ],\n    "total": 2,\n    "page": 1\n  }\n}',
  '{\n  "compilerOptions": {\n    "target": "ES2020",\n    "module": "commonjs",\n    "strict": true,\n    "outDir": "./dist"\n  },\n  "include": ["src/**/*"]\n}',
  '[\n  {"name": "server1", "ip": "10.0.1.1", "region": "us-east"},\n  {"name": "server2", "ip": "10.0.1.2", "region": "us-west"}\n]',
  '{\n  "endpoint": "https://api.example.com/v2",\n  "timeout": 5000,\n  "retry": {\n    "count": 3,\n    "backoff": "exponential"\n  }\n}',
  '{\n  "type": "Feature",\n  "geometry": { "type": "Point", "coordinates": [102.0, 0.5] },\n  "properties": { "name": "Example Location" }\n}',
  '{\n  "@context": "https://schema.org",\n  "@type": "Organization",\n  "name": "ACME Corp",\n  "url": "https://acme.example.com",\n  "logo": "https://acme.example.com/logo.png"\n}',
  '{\n  "title": "Person",\n  "type": "object",\n  "properties": {\n    "name": { "type": "string" },\n    "age": { "type": "integer", "minimum": 0 },\n    "email": { "type": "string", "format": "email" }\n  },\n  "required": ["name", "email"]\n}',
  '{\n  "users": [\n    { "id": 1, "profile": { "displayName": "Alice", "avatar": null }, "tags": ["staff"] },\n    { "id": 2, "profile": { "displayName": "Bob", "avatar": "/img/bob.png" }, "tags": [] }\n  ]\n}',
  '{\n  "log": {\n    "level": "error",\n    "message": "Connection refused",\n    "timestamp": "2024-06-15T10:30:00Z",\n    "service": "auth",\n    "trace_id": "abc-123-def"\n  }\n}',
  '{\n  "type": "FeatureCollection",\n  "features": [\n    { "type": "Feature", "geometry": { "type": "LineString", "coordinates": [[0,0],[1,1]] } }\n  ]\n}',
  '{\n  "$schema": "https://json-schema.org/draft/2020-12/schema",\n  "$id": "https://example.com/product.schema.json",\n  "type": "object",\n  "properties": {\n    "productId": { "type": "integer" },\n    "price": { "type": "number", "exclusiveMinimum": 0 }\n  }\n}',
  '{\n  "data": {\n    "attributes": {\n      "nested": {\n        "deeply": {\n          "value": 42\n        }\n      }\n    }\n  }\n}',
  '[\n  {"op": "replace", "path": "/name", "value": "New Name"},\n  {"op": "add", "path": "/tags/-", "value": "featured"}\n]',
  '{\n  "swagger": "2.0",\n  "info": { "title": "My API", "version": "1.0.0" },\n  "paths": {\n    "/users": { "get": { "summary": "List users" } }\n  }\n}',
];
