export const linux: string[] = [
  "journalctl -u nginx.service --since \"1 hour ago\" --no-pager | grep -i error | tail -20",
  "systemctl status postgresql-16\n● postgresql-16.service - PostgreSQL 16 database server\n   Loaded: loaded /usr/lib/systemd/system/postgresql-16.service\n   Active: active (running) since Mon 2024-03-18 10:23:45 UTC",
  "journalctl --follow -u docker.service -n 50 --output=short-iso",
  "nmcli device wifi list --rescan yes | grep -E '^\\*|5 GHz' | head -10",
  "ss -tulpn | grep -E ':(80|443|3000|5432)' | awk '{print $1, $4, $7}'",
  "iptables -A INPUT -p tcp --dport 22 -s 192.168.1.0/24 -j ACCEPT\niptables -A INPUT -p tcp --dport 22 -j DROP",
  "rsync -avz --progress --partial --delete -e \"ssh -p 2222 -i ~/.ssh/deploy_key\" ./dist/ user@server:/var/www/html/",
  "tmux new-session -d -s dev\ntmux send-keys -t dev 'cd /project && npm run dev' Enter\ntmux split-window -h -t dev\ntmux send-keys -t dev 'npm run test:watch' Enter",
  "strace -f -e trace=openat,read,write -p 12345 -o /tmp/strace.log 2>&1 | grep -v ENOENT",
  "lsof -i :3000\nlsof -iTCP -sTCP:LISTEN -P -n | awk '{print $1, $2, $9}'",
  "find /var/log -name \"*.log\" -mtime +30 -exec gzip {} \\;\nfind . -type f -name \"*.pyc\" -delete",
  "htop -u $(whoami) --sort-key PERCENT_CPU --tree\nkill -9 $(lsof -t -i:3000) 2>/dev/null || echo \"Port 3000 is free\"",
  "df -h | grep -E '^(/dev|tmpfs)'\ndu -sh /var/log/* | sort -rh | head -10",
  "tar -czf backup_$(date +%Y%m%d_%H%M).tar.gz --exclude=node_modules --exclude=.next ./project/",
  "ping -c 4 -W 2 google.com\ncurl -s -o /dev/null -w \"%{http_code} %{time_total}s\" https://api.example.com/health",
];
