export const markdown: string[] = [
  "# Project Title\n\n## Table of Contents\n- [Installation](#installation)\n- [Usage](#usage)\n- [API](#api)\n- [Contributing](#contributing)\n- [License](#license)",
  "| Method | Endpoint | Description | Auth |\n|--------|----------|-------------|------|\n| GET | /api/users | List users | Bearer |\n| POST | /api/users | Create user | Bearer |\n| DELETE | /api/users/:id | Remove user | Admin |",
  "- [x] Implement user authentication\n- [x] Add database migrations\n- [ ] Write API documentation\n- [ ] Set up CI/CD pipeline\n- [ ] Performance audit",
  "Here is a footnote reference[^1] and another[^2].\n\n[^1]: This is the first footnote.\n[^2]: This is the second footnote with **formatting**.",
  "Term\n:   This is the definition of the term.\n\nMarkup Language\n:   A system for annotating a document in a way that is syntactically distinguishable from the text.",
  "```mermaid\ngraph TD\n    A[Start] --> B{Is it working?}\n    B -->|Yes| C[Deploy]\n    B -->|No| D[Debug]\n    D --> B\n```",
  "> [!NOTE]\n> This is a note with additional information for the reader.\n\n> [!WARNING]\n> This operation cannot be undone. Make sure you have a backup.",
  "<details>\n<summary>Click to expand code example</summary>\n\n```python\ndef hello():\n    print(\"Hello, World!\")\n```\n\n</details>",
  "[![Build Status](https://img.shields.io/github/actions/workflow/status/user/repo/ci.yml)](https://github.com/user/repo/actions)\n[![npm version](https://img.shields.io/npm/v/package.svg)](https://www.npmjs.com/package/package)",
  "The quadratic formula is $$x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}$$ and the sum is $\\sum_{i=1}^{n} i = \\frac{n(n+1)}{2}$.",
  "### Code Examples\n\n#### JavaScript\n```javascript\nconst greet = (name) => {\n  return `Hello, ${name}!`;\n};\n```\n\n#### Python\n```python\ndef greet(name):\n    return f\"Hello, {name}!\"\n```",
  "> This is a blockquote with multiple paragraphs.\n>\n> This is the second paragraph of the blockquote.\n>\n> > And this is a nested blockquote for emphasis.",
  "1. First item\n2. Second item\n   1. Indented item\n   2. Another indented item\n3. Third item with **bold** text and *italic* text.",
  "---\n\n### Horizontal Rule Above\n\n#### Emoji Support :rocket: :fire: :zap:\n\n#### Subscript: H~2~O and Superscript: X^2^",
  "### Links\n\nCheck out the [documentation](https://docs.example.com) for more details.\n\nImages: ![Alt text](/images/screenshot.png \"Optional title\")",
];
