export const mongodb: string[] = [
  "db.users.find({ age: { $gte: 18 } }, { name: 1, email: 1 }).sort({ name: 1 }).limit(10);",
  "db.orders.aggregate([\n    { $match: { status: 'shipped' } },\n    { $group: { _id: '$customer_id', total: { $sum: '$amount' } } },\n    { $sort: { total: -1 } }\n]);",
  "db.orders.aggregate([\n    { $lookup: { from: 'users', localField: 'user_id', foreignField: '_id', as: 'user' } },\n    { $unwind: '$user' }\n]);",
  "db.users.createIndex({ email: 1 }, { unique: true });\ndb.users.createIndex({ location: '2dsphere' });",
  "db.inventory.updateMany(\n    { quantity: { $lt: 10 } },\n    { $set: { restock: true }, $inc: { restock_count: 1 } }\n);",
  "db.orders.aggregate([\n    { $group: { _id: '$status', count: { $sum: 1 }, total: { $sum: '$amount' } } },\n    { $sort: { total: -1 } }\n]);",
  "db.orders.aggregate([\n    { $lookup: { from: 'users', let: { uid: '$user_id' },\n        pipeline: [{ $match: { $expr: { $eq: ['$_id', '$$uid'] } } }], as: 'user' } }\n]);",
  "db.sales.aggregate([\n    { $facet: {\n        byCategory: [{ $group: { _id: '$category', total: { $sum: '$amount' } } }],\n        byYear: [{ $group: { _id: { $year: '$date' }, total: { $sum: '$amount' } } }]\n    } }\n]);",
  "db.transactions.aggregate([\n    { $bucket: { groupBy: '$amount', boundaries: [0, 100, 500, 1000], default: 'Other', output: { count: { $sum: 1 } } } }\n]);",
  "db.orders.aggregate([\n    { $match: { status: 'shipped' } },\n    { $merge: { into: 'shipped_orders', whenMatched: 'merge', whenNotMatched: 'insert' } }\n]);",
  "db.users.aggregate([\n    { $project: { fullName: { $concat: ['$firstName', ' ', '$lastName'] }, age: { $subtract: [new Date(), '$dob'] } } }\n]);",
  "db.orders.aggregate([\n    { $unwind: '$items' },\n    { $group: { _id: '$items.product', totalSold: { $sum: '$items.quantity' } } },\n    { $sort: { totalSold: -1 } },\n    { $limit: 10 }\n]);",
  "db.inventory.aggregate([\n    { $addFields: { discounted: { $multiply: ['$price', 0.9] } } },\n    { $match: { discounted: { $lt: 50 } } }\n]);",
  "db.events.createIndex({ location: '2dsphere', date: 1 });\ndb.events.find({ location: { $near: { $geometry: { type: 'Point', coordinates: [-73.97, 40.77] }, $maxDistance: 1000 } } });",
  "db.orders.aggregate([\n    { $group: { _id: null, avgAmount: { $avg: '$amount' }, maxAmount: { $max: '$amount' }, minAmount: { $min: '$amount' } } }\n]);",
];
