export const python: string[] = [
  "def fibonacci(n: int) -> int:\n    if n <= 1:\n        return n\n    return fibonacci(n - 1) + fibonacci(n - 2)",
  "async def fetch_user_data(user_id: str) -> dict:\n    async with aiohttp.ClientSession() as session:\n        async with session.get(f'/api/users/{user_id}') as resp:\n            return await resp.json()",
  "def validate_email(email: str) -> bool:\n    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$'\n    return bool(re.match(pattern, email))",
  "with open('config.json', 'r') as f:\n    config = json.load(f)\n    database_url = config.get('database', {}).get('url')\n    if not database_url:\n        raise ValueError('Database URL not configured')",
  "@dataclass\nclass User:\n    id: str\n    name: str\n    email: str\n    created_at: datetime\n\n    def to_dict(self) -> dict:\n        return {'id': self.id, 'name': self.name, 'email': self.email}",
  "from typing import Generator\ndef fibonacci(n: int) -> Generator[int, None, None]:\n    a, b = 0, 1\n    for _ in range(n):\n        yield a\n        a, b = b, a + b",
  "async def gather_tasks():\n    results = await asyncio.gather(\n        fetch_user(1), fetch_user(2), fetch_user(3), return_exceptions=True\n    )",
  "@property\ndef full_name(self) -> str:\n    return f'{self.first_name} {self.last_name}'.strip()",
  "with contextlib.suppress(FileNotFoundError):\n    os.remove('temp_file.txt')",
  "def divide(a: int, b: int) -> float:\n    if b == 0:\n        raise ValueError('Cannot divide by zero')\n    return a / b",
  "@lru_cache(maxsize=128)\ndef compute_expensive(x: int) -> int:\n    return sum(i * i for i in range(x))",
  "match command.split():\n    case ['quit']: sys.exit(0)\n    case ['hello', name]: print(f'Hello {name}')\n    case _: print('Unknown command')",
  "class BaseConfig:\n    pass\n\nclass DevConfig(BaseConfig):\n    DEBUG = True\n\nclass ProdConfig(BaseConfig):\n    DEBUG = False",
  "a: list[int] = [1, 2, 3]\nb: dict[str, float] = {'pi': 3.14, 'e': 2.71}\nc: set[int] = {1, 2, 3}",
  "async def stream_data() -> AsyncGenerator[bytes, None]:\n    async with aiofiles.open('large.bin', 'rb') as f:\n        while chunk := await f.read(8192):\n            yield chunk",
];
