export const react: string[] = [
  "function Counter() {\n    const [count, setCount] = useState(0);\n    return <button onClick={() => setCount(c => c + 1)}>{count}</button>;\n}",
  "interface Props {\n    userId: string;\n    onError?: (err: Error) => void;\n}\n\nfunction UserProfile({ userId, onError }: Props) {\n    const [user, setUser] = useState<User | null>(null);\n    useEffect(() => {\n        fetch(`/api/users/${userId}`)\n            .then(res => res.json())\n            .then(setUser)\n            .catch(onError);\n    }, [userId]);\n    return user ? <div>{user.name}</div> : <Spinner />;\n}",
  "const ThemeContext = createContext('light');\n\nfunction App() {\n    return (\n        <ThemeContext.Provider value=\"dark\">\n            <Toolbar />\n        </ThemeContext.Provider>\n    );\n}",
  "function useLocalStorage<T>(key: string, initial: T): [T, (val: T) => void] {\n    const [value, setValue] = useState<T>(() => {\n        const stored = localStorage.getItem(key);\n        return stored ? JSON.parse(stored) : initial;\n    });\n    useEffect(() => localStorage.setItem(key, JSON.stringify(value)), [key, value]);\n    return [value, setValue];\n}",
  "const TodoList = () => {\n    const [todos, setTodos] = useState<string[]>([]);\n    const addTodo = (text: string) => setTodos(prev => [...prev, text]);\n    return (\n        <ul>{todos.map((t, i) => <li key={i}>{t}</li>)}</ul>\n    );\n};",
  "function ProfilePage({ userId }) {\n    const [optimisticName, setOptimisticName] = useOptimistic(userName);\n    return <div>{optimisticName}</div>;\n}",
  "function Tabs() {\n    const [tab, setTab] = useState('home');\n    const [isPending, startTransition] = useTransition();\n    return <button onClick={() => startTransition(() => setTab('settings'))}>Switch</button>;\n}",
  "const FancyButton = forwardRef<HTMLButtonElement, Props>((props, ref) => (\n    <button ref={ref} className=\"fancy\">{props.children}</button>\n));",
  "async function ProfilePage({ userId }) {\n    const user = await fetchUser(userId);\n    return <div>{user.name}</div>;\n}",
  "function App() {\n    return (\n        <Suspense fallback={<Spinner />}>\n            <ProfilePage />\n        </Suspense>\n    );\n}",
  "function Form() {\n    const [state, formAction] = useActionState(updateName, { error: null });\n    return <form action={formAction}><input name=\"name\" /></form>;\n}",
  "const ctx = createContext({ theme: 'light', toggleTheme: () => {} });\nfunction useTheme() { return useContext(ctx); }",
  "function List({ items }: { items: Item[] }) {\n    return items.map(item => <li key={item.id}>{item.name}</li>);\n}",
  "const memoized = useMemo(() => computeExpensive(a, b), [a, b]);\nconst handler = useCallback((e) => console.log(e), []);",
  "function ErrorBoundary({ children }) {\n    return <ErrorBoundary fallback={<h1>Something went wrong</h1>}>{children}</ErrorBoundary>;\n}",
];
