export const sql: string[] = [
  "SELECT u.name, o.total\nFROM users u\nINNER JOIN orders o ON u.id = o.user_id\nWHERE o.status = 'completed'\nORDER BY o.total DESC;",
  "SELECT department, AVG(salary) as avg_salary\nFROM employees\nGROUP BY department\nHAVING AVG(salary) > 80000;",
  "WITH ranked AS (\n    SELECT *, ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rn\n    FROM employees\n)\nSELECT * FROM ranked WHERE rn <= 3;",
  "SELECT * FROM products\nWHERE category_id IN (\n    SELECT id FROM categories WHERE active = 1\n);",
  "SELECT\nto_char(created_at, 'YYYY-MM') AS month,\nCOUNT(*) AS total,\nSUM(amount) AS revenue\nFROM transactions\nGROUP BY month\nORDER BY month;",
  "WITH RECURSIVE org_tree AS (\n    SELECT id, name, 0 AS depth FROM employees WHERE manager_id IS NULL\n    UNION ALL\n    SELECT e.id, e.name, ot.depth + 1 FROM employees e JOIN org_tree ot ON e.manager_id = ot.id\n)\nSELECT * FROM org_tree;",
  "MERGE INTO inventory AS target\nUSING new_shipments AS source\nON target.product_id = source.product_id\nWHEN MATCHED THEN UPDATE SET target.quantity = target.quantity + source.quantity\nWHEN NOT MATCHED THEN INSERT (product_id, quantity) VALUES (source.product_id, source.quantity);",
  "SELECT user_id, amount,\n    AVG(amount) OVER (PARTITION BY user_id ORDER BY created_at ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS moving_avg\nFROM transactions;",
  "SELECT * FROM documents\nWHERE to_tsvector('english', content) @@ to_tsquery('english', 'database & performance');",
  "SELECT department, employee_id, salary,\n    SUM(salary) OVER (PARTITION BY department ORDER BY salary ROWS UNBOUNDED PRECEDING) AS running_total\nFROM employees;",
  "UPDATE products SET price = price * 1.1 WHERE category = 'electronics';\nDELETE FROM sessions WHERE expires_at < NOW();",
  "SELECT * FROM (\n    SELECT *, ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary DESC) AS rn\n    FROM employees\n) sub WHERE rn <= 5;",
  "INSERT INTO audit_log (table_name, action, old_data, new_data)\nVALUES ('users', 'UPDATE', row_to_json(OLD), row_to_json(NEW));",
  "CREATE INDEX idx_users_email ON users USING btree (email);\nCREATE INDEX idx_orders_date ON orders USING btree (created_at DESC);",
  "SELECT o.id, JSON_AGG(JSON_BUILD_OBJECT('product', p.name, 'qty', oi.quantity)) AS items\nFROM orders o JOIN order_items oi ON o.id = oi.order_id\nJOIN products p ON oi.product_id = p.id\nGROUP BY o.id;",
];
