export const stacktraces: string[] = [
  "Traceback (most recent call last):\n  File \"/app/main.py\", line 42, in process_order\n    result = calculate_total(items)\n  File \"/app/utils.py\", line 18, in calculate_total\n    return sum(item['price'] for item in items)\nKeyError: 'price'",
  "java.lang.NullPointerException: Cannot invoke \"String.length()\" because \"name\" is null\n    at com.example.UserService.greet(UserService.java:25)\n    at com.example.UserController.getUser(UserController.java:15)\n    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Native Method)",
  "TypeError: Cannot read properties of undefined (reading 'id')\n    at renderUser (/app/src/components/UserProfile.tsx:34:18)\n    at updateFunctionComponent (/app/node_modules/react-dom/cjs/react-dom.development.js:7356:14)",
  "panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a1b2c]\n\ngoroutine 1 [running]:\nmain.main()\n        /app/main.go:42 +0x1a3",
  "thread 'main' panicked at src/main.rs:34:9:\nindex out of bounds: the len is 5 but the index is 10\nstack backtrace:\n   0: rust_begin_unwind\n   1: core::panicking::panic_fmt\n   2: core::panicking::panic_bounds_check",
  "Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.\n   at MyApp.Services.OrderService.ProcessOrder(Order order) in /app/Services/OrderService.cs:line 56",
  "/app/app/models/user.rb:45:in `save': Validation failed: Email has already been taken (ActiveRecord::RecordNotUnique)\n    from /app/app/controllers/users_controller.rb:22:in `create'",
  "Fatal error: Uncaught TypeError: Return value of App\\Service\\Payment::process() must be an instance of App\\Service\\PaymentResponse, bool returned in /var/www/html/app/Service/Payment.php:89",
  "error: Could not find the correct provider for `this` context\n    at Object.ScheduleWidget.build (/app/lib/schedule_widget.dart:78:5)\n    at WidgetBuilder.build (_SchedulePageState.dart:42:12)",
  "java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (USERS.UK_EMAIL) violated\n    at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)\n    at org.hibernate.exception.ConstraintViolationException.convert(ConstraintViolationException.java:59)",
  "Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userService' defined in file [/app/UserService.class]: Initialization of bean failed",
  "ModuleNotFoundError: No module named 'app.routes.admin'\n  File \"/app/venv/lib/python3.12/site-packages/flask/cli.py\", line 245, in find_best_app\n    run_command",
  "ERROR: Gems missing: gem install bundler\nInstalling required dependencies...\nAn error occurred while installing pg (1.5.6), and Bundler cannot continue.",
  "[webpack.cache.PackFileCacheStrategy] Caching failed. PackFileCacheStrategy has reached the limit of stored files. Cache will be cleared.",
  "Error: ENOSPC: System limit for number of file watchers reached\n    at FSWatcher.start (internal/fs/watchers.js:179:19)\n    at watch (internal/fs/watchers.js:153:10)\n    at Object.watch (fs.js:1465:34)",
];
