export const terminal: string[] = [
  "cat package.json | jq '.dependencies | keys | .[]' | sort | head -20",
  "curl -s https://api.github.com/repos/user/repo/releases/latest | jq '.tag_name, .published_at, .assets[].name'",
  "rg --type ts \"function use[A-Z]\" --stats --no-heading src/hooks/ | sort | uniq -c | sort -rn | head -15",
  "fd --extension ts --extension tsx --exclude node_modules --exclude .next -x wc -l {} | awk '{sum+=$1} END {print sum \" total lines\"}'",
  "bat --paging=never --theme=Dracula --language=typescript src/components/typing/TypingEngine.tsx | head -60",
  "npm ls --depth=0 --all 2>/dev/null | grep -E '^[├└]' | wc -l",
  "fzf --preview 'bat --color=always --style=numbers {}' --bind 'ctrl-space:toggle-preview'",
  "http GET https://api.example.com/users Authorization:'Bearer token123' | jq '.data[] | {id, name, email}'",
  "zoxide query -l /project | fzf --bind 'enter:become(nvim {})'",
  "find . -name \"package.json\" -not -path \"*/node_modules/*\" -exec sh -c 'echo \"$1: $(jq \".version\" $1)\"' _ {} \\;",
  "pandoc README.md -o README.pdf --pdf-engine=xelatex -V mainfont=\"DejaVu Sans\"",
  "grep -r \"TODO\\|FIXME\\|HACK\" --include=\"*.ts\" --include=\"*.tsx\" --exclude-dir=node_modules --exclude-dir=.next . | wc -l",
  "htop -u $(whoami) --tree --sort-key PERCENT_MEM",
  "lazygit -g status -b main -w -p",
  "curl -X POST https://api.example.com/deploy -H \"Authorization: Bearer $DEPLOY_TOKEN\" -d '{\"branch\":\"main\",\"ref\":\"HEAD\"}' | jq '.status, .url'",
];
