export const typescript: string[] = [
  "interface User {\n    id: string;\n    name: string;\n    email: string;\n    role: 'admin' | 'user';\n    createdAt: Date;\n}",
  "function identity<T>(arg: T): T {\n    return arg;\n}",
  "type PartialUser = Partial<User>;\ntype ReadonlyUser = Readonly<User>;\ntype UserName = Pick<User, 'name'>;\ntype WithoutEmail = Omit<User, 'email'>;",
  "function isAdmin(user: User): user is User & { role: 'admin' } {\n    return user.role === 'admin';\n}",
  "enum HttpStatus {\n    OK = 200,\n    CREATED = 201,\n    BAD_REQUEST = 400,\n    UNAUTHORIZED = 401,\n    NOT_FOUND = 404,\n    INTERNAL_ERROR = 500,\n}",
  "type EventName = 'click' | 'focus' | 'blur';\ntype EventHandler = `on${Capitalize<EventName>}`;",
  "type IsString<T> = T extends string ? true : false;\ntype Result = IsString<'hello'>;",
  "const config = { host: 'localhost', port: 8080 } satisfies AppConfig;",
  "function tuple<T extends readonly unknown[]>(...args: T): T {\n    return args;\n}\nconst t = tuple(1, 'a', true);",
  "type DeepReadonly<T> = {\n    readonly [K in keyof T]: T[K] extends object ? DeepReadonly<T[K]> : T[K];\n};",
  "type Brand<T, B> = T & { __brand: B };\ntype UserId = Brand<string, 'UserId'>;\nfunction getUser(id: UserId) {}",
  "type ApiResponse<T> = { data: T; error: null } | { data: null; error: string };",
  "const box = <T,>(value: T): { value: T } => ({ value });",
  "type RequiredBy<T, K extends keyof T> = Omit<T, K> & { [P in K]-?: T[P] };",
  "const obj = { a: 1, b: 'hello' } as const;\ntype ObjType = typeof obj;",
];
